org.gradle.jvmargs = -Xmx3G
org.gradle.parallel = true
org.gradle.caching = true

minecraft_version = 1.20.1
forge_version = 47.4.1
mapping_channel = parchment
mapping_version = 2023.09.03

# Mod Properties
mod_version = 0.1
maven_group = tech.vixhentx.mcmod
archives_base_name = CTNH-Lib
mod_id = ctnhlib
mod_name = CTNH Lib
mod_url = https://github.com/CTNH-Team/CTNH-Lib
mod_author = CTNH Team
mod_description = Common library mod for core mods of modpack Create: New Horizon
mod_license = MIT
